services:
  virtual_binder:
    build: 
        context: ./
        dockerfile: ./virtual_binder/Dockerfile
    ports:
      - "5006:5006"
  decks:
    build: 
        context: ./
        dockerfile: ./deck_analysis/Dockerfile
  decks-dev:
    ports:
      - "5006:5006"
    volumes:
      - .:/app
    build: 
        context: ./
        dockerfile: ./deck_analysis/Dockerfile.dev